name: Build ALL
run-name: Build ALL
on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  Build_IOS:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: |
          mkdir -p /Users/runner/work/venera/venera/build/ios/iphoneos/Payload
          mv /Users/runner/work/venera/venera/build/ios/iphoneos/Runner.app /Users/runner/work/venera/venera/build/ios/iphoneos/Payload
          cd /Users/runner/work/venera/venera/build/ios/iphoneos/
          zip -r venera-ios.ipa Payload
      - name: Add version to filename
        run: |
          APP_VERSION=$(grep "version:" pubspec.yaml | cut -d':' -f2 | tr -d ' ')
          mkdir -p result
          mv build/ios/iphoneos/venera-ios.ipa result/venera-ios-$APP_VERSION.ipa
      - uses: actions/upload-artifact@v4
        with:
          name: ios_build
          path: result/
  Build_Android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - name: Decode and install certificate
        env:
          STORE_FILE: ${{ secrets.ANDROID_KEYSTORE }}
          PROPERTY_FILE: ${{ secrets.ANDROID_KEY_PROPERTIES }}
        run: |
            echo "$STORE_FILE" | base64 --decode > android/keystore.jks
            echo "$PROPERTY_FILE" > android/key.properties
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Check rust-toolchain.toml
        run: rustup show
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: apks
          path: build/app/outputs/apk/release

  Release:
    runs-on: ubuntu-22.04
    needs: [Build_IOS, Build_Android]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ios_build
          path: outputs
      - uses: actions/download-artifact@v4
        with:
          name: apks
          path: outputs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
